FROM php:8.2.20-apache

# Atualize os pacotes do sistema para corrigir vulnerabilidades
RUN apt-get update && apt-get upgrade -y && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instale extensões necessárias
RUN docker-php-ext-install pdo pdo_mysql

# Instale Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copie o código para o container
COPY . /var/www/html

# Dê permissão para o storage e cache
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Habilite o mod_rewrite do Apache
RUN a2enmod rewrite

EXPOSE 80
