#version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - node
    environment:
      - DB_HOST=db
      - DB_DATABASE=michelangelo_bd_local
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:16
    container_name: postgres-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: michelangelo_bd_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  node:
    image: node:20
    working_dir: /var/www/html
    volumes:
    - .:/var/www/html
    command: sh -c "npm install && npm run build"

volumes:
  dbdata:
